# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: kontoapi-rails 0.3.0 ruby lib

Gem::Specification.new do |s|
  s.name = "kontoapi-rails".freeze
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Jan Schwenzien".freeze]
  s.date = "2016-12-01"
  s.description = "This library is a wrapper for the Konto API (https://www.kontoapi.de/). It provides a validation method for models that checks if a given account number and bank code represent a valid combination.".freeze
  s.email = "jan@schwenzien.org".freeze
  s.extra_rdoc_files = [
    "LICENSE",
    "README.markdown"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "init.rb",
    "kontoapi-rails.gemspec",
    "lib/kontoapi-rails.rb",
    "lib/kontoapi-rails/config.rb",
    "lib/kontoapi-rails/orm/active_record_extension.rb",
    "lib/kontoapi-rails/orm/mongoid_extension.rb",
    "lib/kontoapi-rails/railtie.rb",
    "lib/kontoapi-rails/validators/bank_account_validator.rb",
    "spec/kontoapi-rails_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/GeneralScripting/kontoapi-rails".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "2.6.7".freeze
  s.summary = "A wrapper for the Konto API (https://www.kontoapi.de/) providing model validation.".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>.freeze, [">= 3.0.0"])
      s.add_runtime_dependency(%q<kontoapi-ruby>.freeze, [">= 0.2.0"])
      s.add_development_dependency(%q<rspec>.freeze, [">= 2.3.0"])
      s.add_development_dependency(%q<bundler>.freeze, [">= 1.1.0"])
      s.add_development_dependency(%q<jeweler>.freeze, [">= 1.5.2"])
      s.add_development_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_development_dependency(%q<rdoc>.freeze, [">= 0"])
    else
      s.add_dependency(%q<rails>.freeze, [">= 3.0.0"])
      s.add_dependency(%q<kontoapi-ruby>.freeze, [">= 0.2.0"])
      s.add_dependency(%q<rspec>.freeze, [">= 2.3.0"])
      s.add_dependency(%q<bundler>.freeze, [">= 1.1.0"])
      s.add_dependency(%q<jeweler>.freeze, [">= 1.5.2"])
      s.add_dependency(%q<simplecov>.freeze, [">= 0"])
      s.add_dependency(%q<rdoc>.freeze, [">= 0"])
    end
  else
    s.add_dependency(%q<rails>.freeze, [">= 3.0.0"])
    s.add_dependency(%q<kontoapi-ruby>.freeze, [">= 0.2.0"])
    s.add_dependency(%q<rspec>.freeze, [">= 2.3.0"])
    s.add_dependency(%q<bundler>.freeze, [">= 1.1.0"])
    s.add_dependency(%q<jeweler>.freeze, [">= 1.5.2"])
    s.add_dependency(%q<simplecov>.freeze, [">= 0"])
    s.add_dependency(%q<rdoc>.freeze, [">= 0"])
  end
end

